'''
    Substitutable Graph Learning - An Implementation
    Author : Katie Rischpater (katie.risc@gmail.com)
    Updated : 6-13-22

    Purpose: 
        This script is an implementation of the substitution 
        graphs and the algorithms detailed within Clark & Eyraud's 
        paper 'Polynomial Identification in the Limit of Substitutable
        Context-free Languages' (https://aclanthology.org/W16-5901.pdf)
        The goal of this script is to emulate the implementation of
        Algorithms 1 & 2 detailed in Section 3.1.  Furthermore, in
        order to implement these, a framework for representing CFGs 
        and Substitution Graphs has been given in the classes detailed
        below.

    Comment Notation:
        :       "such that" (not to be confused with the dict {a : b})
        0.0     "Section 0.0 of Clark & Eyraud"
        ||      "Divider between datatype & Explanation"
        Sig.    "Sigma, the given alphabet of a Grammar / Graph"

    Kay's Personal Notes:
        @ 6-12-22, 21:57: I can't help but see some similarities
            between the parsing of a string for an SG and a 3-Gram
            Strictly-Local Grammar.  In both instances, the grammar
            is generated by searching linearly through a string, and
            analyzing tuples.  Where an SG only looks at internal
            relations - e.g., lur / lvr in S, a 3-Gram grammar is
            interested in the tuples, and a transition such as
            (lur) -> (urt).  I don't believe there is anything
            that is terribly significant about this, but it was
            an interesting coincidence!  Maybe it's worth exploring
            a graph abstraction for N-Gram languages in a similar
            way that this paper compares SGs and CFGs.
            Also, is there any way we can abstract this style of
            substitutable language learning to MGs and MCFGs? I
            think it might be rather difficult, as the whole point
            is they... *don't* have a context, however I'd be
            curious to see if we could still draw parallels :)
            
'''

# SG(S) = (V, E) - Defined in 3.0
class Substitution_Graph:
    # s = ['strings'] ' || e.g., the toy ['abba'], or 
    # [['The','man','walked']] for full words
    def __init__(self, name, s):
        contexts = {} # {(l, r) : {u, v, ...}} || edge (u, v) for strs
                      # 'lur' 'lvr' in Sig.
        # This is the quadratic bottlneck to the graph 
        # creation; we need to check each 'word' (or sentence,
        # depending on the corpus) in the sequence S, and each W must
        # be divided into substrings. - 7.1, Par 1 
        for w in s:
            for i in range(1, len(w) - 1):
                substr = w[i-1:i+2] # gets a substr x : |x| = 3
                con = (substr[0], substr[2])
                if con not in contexts:
                    contexts[con] = {substr[1]}
                else:
                    contexts[con].add(substr[1])
        self.name = name
        self.contexts = contexts

    # Formal Def. of a graph, printed with the str it learned from
    def print_formal(self, str):
        verts = set()
        edges = set()
        for c in self.contexts:
            # If component is greater than a single vertex, generate the
            # edges for the coresponding congruence class
            c_class = list(self.contexts[c])
            if(len(c_class) > 1):
                for i in range(0, len(c_class) - 1):
                    pair = (c_class[i], c_class[i+1])
                    edges.add(pair)
            for mid in c:
                verts.update({c[0], c[1], mid})
        print('# ', self.name, ' #\n# ', str,' #\n\nVertices: ', verts,
        '\nEdges:    ', edges,  '\n')
    def print_context(self):
        print("# ", self.name, " Contexts #")
        for c in self.contexts:
            print(c,':', self.contexts[c])


# G = <S, V, P, S> || 2.0, Definition 1
# S = Alphabet, V = NonTerminals,
# P = Finite Production Rules
# S = S is contained in V, subset of start syms
class Grammar:
    def __init__(self, name, alphabet, non_term, term, starts):
        self.name = name
        self.alphabet = alphabet # {'x'}
        self.non_terminals = non_term # {'XP'}
        self.terminals = term # {(XP, rhs, lhs)}
        self.starts = starts # {XP} || S -> X
# Note: For a CFG, S -> (Empty, Empty)
# and P is a subset of (V * X (S U V)+)

# Converts a Substitution Graph to a CFG - 3.1
def algorithm_one(graph):
    pass

# For legibility's sake!
def p_buffer():
    x = '\n'
    for i in range(0,79):
        x += '='
    print(x,'\n')


def main():
    str_1 = ['abbcbba', 'abcba', 'aacaa', 'aaacaaa', 'bbbcbbb']
    sg_1 = Substitution_Graph('SG_1', str_1) # Toy Grammar 1
    # Results Printing...
    sg_1.print_formal(str_1)
    sg_1.print_context()
    p_buffer()

    str_2 = [
        ['the','dog','ran'],
        ['the','cat','ran'],
        ['the','cat','quickly','walked'],
        ['the','cat','slowly','walked'],
    ]
    sg_2 = Substitution_Graph('SG_2', str_2)

    sg_2.print_formal(str_2)
    sg_2.print_context()

    
    '''
    alphabet = {'a', 'b', 'c', 'd', 'e', 'f'}
    str_1 = {'aaa', 'aba', 'bcd', 'bad', 'ddd',  'dfd'}

    # Toy Graph - two distinct components, [abc] & [def]
    vert_1 = {'a', 'b', 'c', 'd', 'e', 'f'}
    edge_1 = {('a','b'),('a','c'), ('d', 'e'), ('d', 'f')}
    '''


if __name__ == '__main__':
    main()